stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: suite-cloud-maven
      pushRemote: true
      registry: 10.0.0.203:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
timeout: 10
notification: {}
