stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: suite-cloud/suite-cloud-maven
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
