stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: wujiaxin159/suite-cloud-maven
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
