stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: suite-cloud-maven
      pushRemote: true
      registry: docker.domain.cn:5000
timeout: 60
notification: {}
